version: '3.8'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1  # Set to 0 in production
    networks:
      - app_network

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app_network
    environment:
      - HOST=0.0.0.0  # This ensures Vue.js can be accessed from outside the container

networks:
  app_network:
    driver: bridge
