# Generated by Django 4.2.6 on 2023-10-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image",
        ),
        migrations.AddField(
            model_name="image",
            name="greyscale_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="greyscale_images/"
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="original_image",
            field=models.ImageField(null=True, upload_to="original_images/"),
        ),
    ]
