# Generated by Django 4.2.6 on 2023-10-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imageapp", "0002_remove_image_image_image_greyscale_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="original_image",
            field=models.ImageField(upload_to="original_images/"),
        ),
    ]
